<!DOCTYPE html>
<html lang="en">
<head>
    <?php $this->display('block/head.phtml', $_arr_tpl_var); ?>
</head>

<?php $this->display('block/header.phtml', $_arr_tpl_var); ?>

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            
            <div class="widget-box collapsible">
                <div class="widget-title">
                    <a href="#collapseOne" data-toggle="collapse" class="collapsed">
                        <span class="icon"><i class="fa fa-search"></i></span>
                        <h5>查询条件</h5>
                    </a>
                </div>
                <div class="collapse" id="collapseOne" style="height: 0px;">
                    <div class="widget-content nopadding">
                        <form action="<?php echo $form_url; ?>" onsubmit="return S.search(this)" method="post"
                              class="form-horizontal">
                            <?php $this->display('block/input.phtml', $_arr_tpl_var); ?>

                            <div class="form-actions">
                                <button type="submit" class="btn btn-primary btn-sm">搜 索</button>
                                <button type="reset" class="btn btn-default btn-sm">重 置</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="nopadding" id="data_tb"></div>
            
        </div>
    </div>


</div>

<script>
    var S = {
        search: function (em) {
            var fm = $(em);

            $.get(fm.attr('action'), fm.serialize(), function (j) {
                if (j.code !=0) {
                    alert(j.msg);
                } else {
                    $('#data_tb').html(j.data)
                }
                
            });

            return false;
        }
    }
</script>

<?php $this->display('block/footer.phtml', []); ?>


