<!DOCTYPE html>
<html lang="en">
<head>
    <?php $this->display('block/head.phtml', $_arr_tpl_var);?>
</head>

<?php $this->display('block/header.phtml', $_arr_tpl_var);?>


        
        
        <div class="row">
            <div class="col-xs-12">
                <div class="alert alert-info">
                    Welcome in the <strong>Unicorn Admin Theme</strong>. Don't forget to check all the pages!
                    <a href="#" data-dismiss="alert" class="close">×</a>
                </div>
                
            </div>
        </div>
        

        




<?php $this->display('block/footer.phtml', []);?>