<meta charset="UTF-8" />
<title><?php echo empty($title)? 'Brick Admin' : $title;?></title>

<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="/static/admin/css/bootstrap.min.css" />
<link rel="stylesheet" href="/static/admin/css/font-awesome.css" />
<link rel="stylesheet" href="/static/admin/css/colorpicker.css" />
<link rel="stylesheet" href="/static/admin/css/datepicker.css" />
<link rel="stylesheet" href="/static/admin/css/icheck/flat/blue.css" />
<link rel="stylesheet" href="/static/admin/css/select2.css" />
<link rel="stylesheet" href="/static/admin/css/jquery-ui.css" />
<link rel="stylesheet" href="/static/admin/css/unicorn.css" />
<!--[if lt IE 9]>
<script type="text/javascript" src="/static/admin/js/respond.min.js"></script>
<![endif]-->





<script src="/static/admin/js/jquery.min.js"></script>
<script src="/static/admin/js/jquery-ui.custom.js"></script>
<script src="/static/admin/js/bootstrap.min.js"></script>
<script src="/static/admin/js/bootstrap-colorpicker.js"></script>
<script src="/static/admin/js/bootstrap-datepicker.js"></script>
<script src="/static/admin/js/jquery.icheck.min.js"></script>
<script src="/static/admin/js/select2.min.js"></script>

<script src="/static/admin/js/jquery.nicescroll.min.js"></script>
<script src="/static/admin/js/unicorn.js"></script>
<script src="/static/admin/js/unicorn.form_common.js"></script>