<body data-color="grey" class="flat">
<div id="wrapper">
    <div id="header">
        <h1><a href="/">Brick Admin</a></h1>
        <a id="menu-trigger" href="#"><i class="fa fa-bars"></i></a>
    </div>

    <div id="user-nav">
        <ul class="btn-group">
            <li class="btn" ><a title="" href="#"><i class="fa fa-user"></i> <span class="text">Profile</span></a></li>
            <li class="btn dropdown" id="menu-messages"><a href="#" data-toggle="dropdown" data-target="#menu-messages" class="dropdown-toggle"><i class="fa fa-envelope"></i> <span class="text">Messages</span> <span class="label label-danger">5</span> <b class="caret"></b></a>
                <ul class="dropdown-menu messages-menu">
                    <li class="title"><i class="fa fa-envelope-alt"></i>Messages<a class="title-btn" href="#" title="Write new message"><i class="fa fa-share"></i></a></li>
                    <li class="message-item">
                        <a href="#">
                            <img alt="User Icon" src="img/demo/av1.jpg" />
                            <div class="message-content">
		                            	<span class="message-time">
			                                3 mins ago
			                            </span>
                                <span class="message-sender">
		                                    Nunc Cenenatis
		                                </span>
                                <span class="message">
		                                    Hi, can you meet me at the office tomorrow morning?
		                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="message-item">
                        <a href="#">
                            <img alt="User Icon" src="img/demo/av1.jpg" />
                            <div class="message-content">
		                            	<span class="message-time">
			                                3 mins ago
			                            </span>
                                <span class="message-sender">
		                                    Nunc Cenenatis
		                                </span>
                                <span class="message">
		                                    Hi, can you meet me at the office tomorrow morning?
		                                </span>
                            </div>
                        </a>
                    </li>
                    <li class="message-item">
                        <a href="#">
                            <img alt="User Icon" src="img/demo/av1.jpg" />
                            <div class="message-content">
		                            	<span class="message-time">
			                                3 mins ago
			                            </span>
                                <span class="message-sender">
		                                    Nunc Cenenatis
		                                </span>
                                <span class="message">
		                                    Hi, can you meet me at the office tomorrow morning?
		                                </span>
                            </div>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="btn"><a title="" href="#"><i class="fa fa-cog"></i> <span class="text">Settings</span></a></li>
            <li class="btn"><a title="" href="login.html"><i class="fa fa-share"></i> <span class="text">Logout</span></a></li>
        </ul>
    </div>

    <div id="sidebar">
        <div id="search">
            <input type="text" placeholder="Search here..."/><button type="submit" class="tip-right" title="Search"><i class="fa fa-search"></i></button>
        </div>
        <ul>
            <li class="active">
                <a href="index.html"><i class="fa fa-home"></i> <span>Dashboard</span></a>
            </li>
            <li class="submenu">
                <a href="#"><i class="fa fa-flask"></i> <span>UI Lab</span> <i class="arrow fa fa-chevron-right"></i></a>
                <ul>
                    <li><a href="interface.html">Interface Elements</a></li>
                    <li><a href="jquery-ui.html">jQuery UI</a></li>
                    <li><a href="buttons.html">Buttons &amp; icons</a></li>
                </ul>
            </li>
            <li class="submenu">
                <a href="#"><i class="fa fa-th-list"></i> <span>Form elements</span> <i class="arrow fa fa-chevron-right"></i></a>
                <ul>
                    <li><a href="form-common.html">Common elements</a></li>
                    <li><a href="form-validation.html">Validation</a></li>
                    <li><a href="form-wizard.html">Wizard</a></li>
                </ul>
            </li>
            <li><a href="tables.html"><i class="fa fa-th"></i> <span>Tables</span></a></li>
            <li><a href="grid.html"><i class="fa fa-th-list"></i> <span>Grid Layout</span></a></li>
            <li class="submenu">
                <a href="#"><i class="fa fa-file"></i> <span>Sample pages</span> <i class="arrow fa fa-chevron-right"></i></a>
                <ul>
                    <li><a href="invoice.html">Invoice</a></li>
                    <li><a href="chat.html">Support chat</a></li>
                    <li><a href="calendar.html">Calendar</a></li>
                    <li><a href="gallery.html">Gallery</a></li>
                    <li><a href="messages.html">Messages</a></li>
                </ul>
            </li>
            <li>
                <a href="charts.html"><i class="fa fa-signal"></i> <span>Charts &amp; graphs</span></a>
            </li>
            <li>
                <a href="widgets.html"><i class="fa fa-inbox"></i> <span>Widgets</span></a>
            </li>
        </ul>

    </div>
    
    <div id="content">
        <div id="content-header" class="mini">
            <h1>Dashboard</h1>
        </div>
        <div id="breadcrumb">
            <a href="#" title="Go to Home" class="tip-bottom"><i class="fa fa-home"></i> Home</a>
            <a href="#" class="current">Dashboard</a>
        </div>
            
            
        
        
    
