<meta charset="UTF-8" />
<title><?php echo empty($title)? 'Brick Admin' : $title;?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="stylesheet" href="/static/admin/css/bootstrap.min.css" />
<link rel="stylesheet" href="/static/admin/css/font-awesome.css" />
<link rel="stylesheet" href="/static/admin/css/fullcalendar.css" />
<link rel="stylesheet" href="/static/admin/css/jquery.jscrollpane.css" />
<link rel="stylesheet" href="/static/admin/css/unicorn.css" />
<!--[if lt IE 9]>
<script type="text/javascript" src="/static/admin/js/respond.min.js"></script>
<![endif]-->

<script src="/static/admin/js/excanvas.min.js"></script>
<script src="/static/admin/js/jquery.min.js"></script>
<script src="/static/admin/js/jquery-ui.custom.js"></script>
<script src="/static/admin/js/bootstrap.min.js"></script>
<script src="/static/admin/js/jquery.flot.min.js"></script>
<script src="/static/admin/js/jquery.flot.resize.min.js"></script>
<script src="/static/admin/js/jquery.sparkline.min.js"></script>
<script src="/static/admin/js/fullcalendar.min.js"></script>

<script src="/static/admin/js/jquery.nicescroll.min.js"></script>
<script src="/static/admin/js/unicorn.js"></script>
<script src="/static/admin/js/unicorn.dashboard.js"></script>